### ISSUE TITLE
make it automatically build on appveyor

### ISSUE THREAD

**Issue by rgl** [coddec/Classic-Shell#6]
it would be nice to have this code build automatically on appveyor.com.

**Comment by coddec** [comment]
@rgl 

> it would be nice to have this code build automatically on appveyor.com.

Created one, not sure if it will work until there's some new code though I guess

**Comment by coddec** [comment]
Everything configured, get following error, tried to upgrade from VS2008 to VS2017 project locally, brings up some warnings. Instead of break anything, I'll wait & see if anyone else can do it correctly without break anything and hopefully can share the procedure with me.

https://ci.appveyor.com/project/coddec/classic-shell/branch/master
`The project file "ClassicExplorer\ClassicExplorer.vcproj" is in the ".vcproj" file format, which MSBuild no longer supports. Please convert the project by opening it in the Visual Studio IDE or running the conversion tool, or use MSBuild 3.5 or earlier to build it.`

# AppVeyor build screenshot
![Screen](https://images2.imgbox.com/06/bd/pozemZzl_o.png)

**Comment by war59312** [comment]
@coddec Could probably get assistance @ https://help.appveyor.com/discussions/problems/7200-specify-which-project-or-solution-file-to-use-because-the-folder-contains-more-than-one-project-or-solution-file

**Comment by coddec** [comment]
@war59312 Thanks for the link, the error is about the version of Visual Studio the project used, I've already resolved multiple project issue mentioned in the link you given. ;)
Cheers

**Comment by IkeKap** [comment]
@coddec what were the specific warnings Visual studio displayed during the conversion process? Also would it be possible to branch off the converted file so it would be easier for multiple people to attempt to resolve the issues as they appear?

**Comment by IkeKap** [comment]
It seems that allowing pull request #7 would open the way to solving this issue @coddec

**Comment by coddec** [comment]
@IkeKap I agree, just waiting someone who can review the changes just in case then we can merge it, hopefully that will resolve this issues too ;)

**Comment by H3rmit** [comment]
so, is anyone going to keep this project alive? I really hope so!

**Comment by XenHat** [comment]
I cannot afford appveyor membership at the moment so my help will be very limited however there is a template for the `.appveyor.yaml` file [here](https://www.appveyor.com/docs/appveyor-yml/) and some alternate instructions from the support staff concerning **multiple projects building** have been provided [in this answer](https://help.appveyor.com/discussions/questions/1544-multiple-solutions-in-a-repository#comment_37538216).

TL;DR:
```yaml
    matrix: 
      - project_name: src/Project1/XXXX.YYY.Project1.sln 
      - project_name: src/Project2/XXXX.YYY.Project2.sln 
      - project_name: src/Project3/XXXX.YYY.Project3.sln 
      - project_name: src/Project4/XXXX.YYY.Project4.sln 
      - project_name: Shared/Foldername/somesolution.sln
```
and then
```yaml
  build: 
    verbosity: normal 
    project: $(project_name)
```
